import json
import re
from datetime import date, datetime, timezone
from uuid import uuid4

from sqlalchemy.orm import Session

from config import CONTACT_EMAIL
from models import (
    DBChore, DBClass, DBClassMembership, DBDailyChoreItem, DBMathAssignment, DBMathTopic,
    DBReadingMaterial, DBRecurringTemplate, DBShopItem, DBShopPurchase, DBSupportTicket, DBUser,
)
from responses import fail


def get_teacher_student(db: Session, teacher_id: str, kid_id: str) -> DBUser:
    """A teacher's "student" is any kid with an approved membership in one of their classes."""
    class_ids = [c.id for c in db.query(DBClass).filter(DBClass.teacher_id == teacher_id).all()]
    if class_ids:
        membership = db.query(DBClassMembership).filter(
            DBClassMembership.kid_id == kid_id, DBClassMembership.class_id.in_(class_ids),
            DBClassMembership.status == "approved",
        ).first()
    else:
        membership = None
    if not membership:
        fail("Student not found in any of your classes", 404)
    kid = db.query(DBUser).filter(DBUser.id == kid_id, DBUser.role == "kid").first()
    if not kid:
        fail("Student not found", 404)
    return kid

POINTS_PER_CORRECT = 3   # shared between Math topics and reading-material quiz questions


def normalize_answer(s: str) -> str:
    s = (s or "").strip().lower().replace(",", "")
    return re.sub(r"\s+", " ", s)


def is_correct_answer(given_answer: str, accepted_answers: list) -> bool:
    """Case/comma/whitespace-insensitive match, also accepting unordered token-set
    matches (e.g. "1, 2, 5, 10" matches "1 2 5 10" regardless of spacing/order)."""
    given = normalize_answer(given_answer)
    given_tokens = set(given.split())
    for accepted in accepted_answers:
        norm = normalize_answer(accepted)
        if given == norm:
            return True
        if given_tokens and given_tokens == set(norm.split()):
            return True
    return False


def grade_answers(questions: list, answers: list) -> tuple:
    """Returns (score, points) for a list of {question, answers:[...]} questions
    against a parallel list of submitted answer strings."""
    score = sum(1 for q, a in zip(questions, answers) if is_correct_answer(a, q["answers"]))
    return score, score * POINTS_PER_CORRECT


def now() -> str:
    return datetime.now(timezone.utc).isoformat()

def calculate_age(dob_str: str) -> int:
    dob = date.fromisoformat(dob_str)
    t   = date.today()
    return t.year - dob.year - ((t.month, t.day) < (dob.month, dob.day))

def calculate_approx_age(birth_month: int, birth_year: int) -> int:
    """Approximate age from birth month/year only (kids don't give an exact day)."""
    t = date.today()
    return t.year - birth_year - (t.month < birth_month)

def get_family_id(user: DBUser) -> str:
    return user.co_guardian_of or user.id

def get_family_owner(db: Session, user: DBUser) -> DBUser:
    """The primary guardian's row — where shared lifetime add-counters live."""
    family_id = user.guardian_id if user.role == "kid" else get_family_id(user)
    return db.query(DBUser).filter(DBUser.id == family_id).first()

def generate_inert_credentials() -> tuple:
    """Kid/co-guardian profiles no longer log in with a username+password — they're
    entered via PIN under the family's device session. `username`/`password`
    stay NOT NULL/unique columns though, so give them harmless, never-shown,
    never-usable placeholder values rather than risking a schema rebuild."""
    return f"profile-{uuid4().hex[:12]}", str(uuid4())

def check_add_limit(db: Session, user: DBUser, field: str, extra: int, limit: int, item_label: str) -> DBUser:
    """Raises 400 if adding `extra` more items would exceed the family's lifetime limit."""
    owner = get_family_owner(db, user)
    current = getattr(owner, field) or 0
    if current + extra > limit:
        fail(
            f"You've reached the limit of {limit} custom {item_label} for your family. "
            f"To add more, please contact our support team at {CONTACT_EMAIL}.",
            403,
        )
    return owner

def safe_user(u: DBUser) -> dict:
    return {"id": u.id, "name": u.name, "username": u.username, "role": u.role,
            "email": u.email, "guardianId": u.guardian_id, "avatar": u.avatar,
            "gender": u.gender, "coGuardianOf": u.co_guardian_of,
            "country": u.country, "city": u.city,
            "lastLoginCountry": u.last_login_country, "lastLoginCity": u.last_login_city,
            "lastLoginAt": u.last_login_at,
            "birthMonth": u.birth_month, "birthYear": u.birth_year,
            "age": calculate_approx_age(u.birth_month, u.birth_year) if (u.birth_month and u.birth_year) else None,
            "createdAt": u.created_at, "lastActiveAt": u.last_active_at,
            "isSuspended": u.is_suspended == "1",
            "requiresPin": u.pin is not None, "pinAutoGenerated": u.pin_auto_generated == "1"}

def chore_dict(c: DBChore) -> dict:
    return {"id": c.id, "title": c.title, "description": c.description,
            "points": c.points, "imageEmoji": c.image_emoji, "status": c.status,
            "assignedKidId": c.assigned_kid_id, "completedByKidId": c.completed_by_kid_id,
            "dueDate": c.due_date, "expiredAt": c.expired_at,
            "completedAt": c.completed_at, "createdAt": c.created_at,
            "templateId": c.template_id, "scheduledDate": c.scheduled_date}

def recurring_dict(t: DBRecurringTemplate) -> dict:
    days = [int(x) for x in t.recurrence_days.split(',') if x.strip()] if t.recurrence_days else []
    return {
        "id": t.id, "title": t.title, "description": t.description,
        "points": t.points, "imageEmoji": t.image_emoji,
        "assignedKidId": t.assigned_kid_id,
        "recurrenceType": t.recurrence_type,
        "recurrenceDays": days,
        "recurrenceDom": int(t.recurrence_dom) if t.recurrence_dom else None,
        "createdAt": t.created_at,
    }

def shop_dict(s: DBShopItem) -> dict:
    return {"id": s.id, "name": s.name, "description": s.description,
            "cost": s.cost, "imageEmoji": s.image_emoji, "createdAt": s.created_at}

def daily_chore_dict(item: DBDailyChoreItem) -> dict:
    return {"id": item.id, "kidId": item.kid_id, "title": item.title,
            "imageEmoji": item.image_emoji, "points": item.points,
            "orderIndex": item.order_index, "status": item.status}

def math_topic_dict(t: DBMathTopic) -> dict:
    questions = json.loads(t.questions)
    return {"id": t.id, "title": t.title, "emoji": t.emoji, "grade": t.grade,
            "explanation": t.explanation,
            "questions": [{"question": q["question"]} for q in questions],
            "questionCount": len(questions)}

def math_assignment_dict(a: DBMathAssignment, topic: DBMathTopic, class_name: str = None) -> dict:
    questions = json.loads(topic.questions)
    submitted = a.submitted_at is not None
    return {
        "id": a.id, "kidId": a.kid_id, "assignedDate": a.assigned_date, "createdAt": a.created_at,
        "dueDate": a.due_date, "classId": a.class_id, "className": class_name,
        "source": a.source or "guardian",
        "topic": {
            "id": topic.id, "title": topic.title, "emoji": topic.emoji, "explanation": topic.explanation,
            "questions": [
                {"question": q["question"], "answer": q["answers"][0] if submitted else None}
                for q in questions
            ],
        },
        "answers": json.loads(a.answers) if a.answers else None,
        "score": a.score, "questionCount": len(questions),
        "pointsEarned": a.points_earned, "submittedAt": a.submitted_at,
    }

def class_dict(c: DBClass) -> dict:
    return {"id": c.id, "teacherId": c.teacher_id, "name": c.name,
            "joinCode": c.join_code, "createdAt": c.created_at}

def membership_dict(m: DBClassMembership, kid: DBUser = None, class_: DBClass = None, guardian: DBUser = None) -> dict:
    return {
        "id": m.id, "classId": m.class_id, "kidId": m.kid_id, "guardianId": m.guardian_id,
        "status": m.status, "requestedAt": m.requested_at, "resolvedAt": m.resolved_at,
        "kidName": kid.name if kid else None, "kidAvatar": kid.avatar if kid else None,
        "className": class_.name if class_ else None,
        "guardianName": guardian.name if guardian else None,
    }

def material_dict(m: DBReadingMaterial, shared_class_ids: list = None, shared_kid_ids: list = None) -> dict:
    """Teacher-facing view — includes full question answers since they authored them."""
    questions = json.loads(m.questions) if m.questions else []
    return {"id": m.id, "teacherId": m.teacher_id, "title": m.title, "description": m.description,
            "url": m.url, "topic": m.topic, "createdAt": m.created_at,
            "questions": questions, "questionCount": len(questions),
            "sharedClassIds": shared_class_ids or [], "sharedKidIds": shared_kid_ids or []}

def material_for_kid_dict(m: DBReadingMaterial, submission=None) -> dict:
    """Kid/guardian-facing view — question answers hidden until the kid submits."""
    questions = json.loads(m.questions) if m.questions else []
    submitted = submission is not None
    return {
        "id": m.id, "title": m.title, "description": m.description, "url": m.url, "topic": m.topic,
        "createdAt": m.created_at, "questionCount": len(questions),
        "questions": [
            {"question": q["question"], "answer": q["answers"][0] if submitted else None}
            for q in questions
        ] if questions else [],
        "submissionId": submission.id if submission else None,
        "answers": json.loads(submission.answers) if (submission and submission.answers) else None,
        "score": submission.score if submission else None,
        "pointsEarned": submission.points_earned if submission else None,
        "submittedAt": submission.submitted_at if submission else None,
    }

def purchase_dict(p: DBShopPurchase) -> dict:
    return {"id": p.id, "kidId": p.kid_id, "shopItemId": p.shop_item_id,
            "itemName": p.item_name, "imageEmoji": p.image_emoji, "cost": p.cost,
            "status": p.status, "createdAt": p.created_at, "resolvedAt": p.resolved_at}

def ticket_dict(t: DBSupportTicket) -> dict:
    return {"id": t.id, "userId": t.user_id, "userName": t.user_name, "username": t.username,
            "userRole": t.user_role, "category": t.category, "subject": t.subject,
            "message": t.message, "status": t.status,
            "createdAt": t.created_at, "resolvedAt": t.resolved_at}
